In [2]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
words=open('names.txt' , 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
len(words)

32033

In [6]:
chars=sorted(list(set(''.join(words))))
stoi={s:i+1 for i,s in enumerate(chars)}
stoi['.']=0
itos={i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [31]:
block_size=3
X,Y=[],[]
for w in words[:5]:
    print(w)
    context=[0]*block_size
    for ch in w:
        ix=stoi[ch]
        X.append(context)
        Y.append(ix)
        print('.'.join(itos[i] for i in context), '--->' , itos[ix])
        context=context[1:]+[ix] 
X=torch.tensor(X)
Y=torch.tensor(Y)

emma
..... ---> e
....e ---> m
..e.m ---> m
e.m.m ---> a
olivia
..... ---> o
....o ---> l
..o.l ---> i
o.l.i ---> v
l.i.v ---> i
i.v.i ---> a
ava
..... ---> a
....a ---> v
..a.v ---> a
isabella
..... ---> i
....i ---> s
..i.s ---> a
i.s.a ---> b
s.a.b ---> e
a.b.e ---> l
b.e.l ---> l
e.l.l ---> a
sophia
..... ---> s
....s ---> o
..s.o ---> p
s.o.p ---> h
o.p.h ---> i
p.h.i ---> a


In [32]:
X.shape,X.dtype,Y.shape,Y.dtype

(torch.Size([27, 3]), torch.int64, torch.Size([27]), torch.int64)

In [33]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9]])

In [34]:
Y

tensor([ 5, 13, 13,  1, 15, 12,  9, 22,  9,  1,  1, 22,  1,  9, 19,  1,  2,  5,
        12, 12,  1, 19, 15, 16,  8,  9,  1])

In [11]:
C=torch.randn((27,2))

In [12]:
C

tensor([[-0.3005, -0.5172],
        [ 0.4591, -0.2221],
        [ 0.1446, -0.1530],
        [ 0.7817,  0.5318],
        [ 0.1068, -0.1917],
        [ 0.4159, -0.6588],
        [-0.2938, -0.3540],
        [-1.4190,  2.1770],
        [-1.5252,  1.2498],
        [ 0.5173,  0.5684],
        [ 0.4687, -0.5617],
        [-0.3140, -1.7493],
        [-1.0590,  0.3370],
        [-0.2224, -0.0540],
        [ 1.5520, -1.0668],
        [-0.1089,  1.0570],
        [ 0.5444,  1.3862],
        [ 0.5235,  1.8499],
        [ 0.8431, -1.4537],
        [ 0.7561,  0.2994],
        [-0.0851, -0.4083],
        [-0.2701, -2.0885],
        [ 0.4893, -0.8583],
        [ 0.3839,  2.1140],
        [-1.5684, -0.3913],
        [ 0.3382,  0.3411],
        [-0.2376, -2.5986]])

In [13]:
C[5]

tensor([ 0.4159, -0.6588])

In [22]:
C[X]

tensor([[[-0.3005, -0.5172],
         [-0.3005, -0.5172],
         [-0.3005, -0.5172]],

        [[-0.3005, -0.5172],
         [-0.3005, -0.5172],
         [ 0.4159, -0.6588]],

        [[-0.3005, -0.5172],
         [ 0.4159, -0.6588],
         [-0.2224, -0.0540]],

        [[ 0.4159, -0.6588],
         [-0.2224, -0.0540],
         [-0.2224, -0.0540]],

        [[-0.3005, -0.5172],
         [-0.3005, -0.5172],
         [-0.3005, -0.5172]],

        [[-0.3005, -0.5172],
         [-0.3005, -0.5172],
         [-0.1089,  1.0570]],

        [[-0.3005, -0.5172],
         [-0.1089,  1.0570],
         [-1.0590,  0.3370]],

        [[-0.1089,  1.0570],
         [-1.0590,  0.3370],
         [ 0.5173,  0.5684]],

        [[-1.0590,  0.3370],
         [ 0.5173,  0.5684],
         [ 0.4893, -0.8583]],

        [[ 0.5173,  0.5684],
         [ 0.4893, -0.8583],
         [ 0.5173,  0.5684]],

        [[-0.3005, -0.5172],
         [-0.3005, -0.5172],
         [-0.3005, -0.5172]],

        [[-0.3005, -0

In [24]:
C[X][13,2]

tensor([-0.3005, -0.5172])

In [28]:
C=torch.randn((27,2))
emb=C[X]
emb.shape

torch.Size([27, 3, 2])

In [35]:
W1=torch.randn((6,100))
b1=torch.randn(100)

In [41]:
torch.cat([emb[:,0,:],emb[:,1,:],emb[:,2,:]],1).shape

torch.Size([27, 6])

In [43]:
a=torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [44]:
a.shape

torch.Size([18])

In [46]:
a.view(2,9)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [47]:
a.storage()

C:\Users\HP\AppData\Local\Temp\ipykernel_25552\214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

In [48]:
emb.shape

torch.Size([27, 3, 2])

In [53]:
h=emb.view(-1,6) @ W1+ b1
h.shape

torch.Size([27, 100])

In [54]:
h=torch.tanh(emb.view(-1,6) @ W1+ b1)

In [55]:
h

tensor([[-0.1920, -1.0000,  0.9562,  ...,  0.0686, -0.9612,  0.9973],
        [ 0.8833, -1.0000,  0.9936,  ..., -0.9891, -0.7889,  0.9214],
        [ 0.9622, -0.7758,  0.5530,  ..., -0.5267, -0.9210,  0.8954],
        ...,
        [-0.9935,  0.2633, -0.9937,  ..., -0.9015, -0.3617,  0.6828],
        [ 0.9995,  0.9998,  0.8740,  ...,  0.4373,  0.9979, -0.9865],
        [-0.7229,  0.9995, -0.9938,  ...,  0.5628,  0.8281, -0.9239]])

In [58]:
h.shape

torch.Size([27, 100])

In [59]:
W2=torch.randn((100,27))
b2=torch.randn(27)

In [60]:
logits=h@W2+b2

In [61]:
logits.shape

torch.Size([27, 27])

In [62]:
logits

tensor([[ -4.3205,   5.0112,  -2.4272,   0.8742,  -5.2660,  -3.0511,  15.4066,
          -4.0705,   1.8100,  25.8262,  -7.8650,  -3.3053,   1.7239,   4.4969,
           5.6029,  -6.1665, -16.2625,   0.3010, -13.4692,   6.8908,  -4.4492,
          -3.7855,   5.6998,  -7.2367,   6.6804,   9.6351,  12.0200],
        [ -9.3038,   2.4586,  -0.1503,   9.3423, -15.3596,  -1.0324,  22.8151,
          -3.0024,   0.3639,  21.2378,  -0.1636,  -6.2499,  10.0156,   0.0606,
           4.5784,  -9.8879, -17.8117,   1.7179,  -6.9043,   7.3320,  -0.2667,
          -2.4138,   9.4575,  -6.7173,   3.0673,   8.7354,   6.6238],
        [ -5.5893,  -0.9494,  12.8660,  -1.9482,  -4.8622, -11.3875,  11.3750,
          -4.2689,   0.2207,  21.6237,  -0.8195,  -7.7874,  -6.5616,  -4.9415,
           8.9949,  -9.9875, -13.4851,  -0.0787,  10.4235,  -7.7136,   3.6122,
          -2.3697,   4.2840,  -3.6030,  -0.8333,   0.2939,   4.3339],
        [-11.2405,   1.2375,   0.7868,  -0.3349,  -1.9589,   6.8138,   3.1044,
